name: Run Tests
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mahdi_todo_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          TEST_DATABASE_URL: "postgresql://postgres:password@localhost:5432/mahdi_todo_test"
          AUTH0_DOMAIN: "mahdi-todo.us.auth0.com"
          AUTH0_API_AUDIENCE: "backend"
          AUTH0_SIGNING_ALGORITHM: "RS256"
        run: python -m unittest
